import { useEffect, useMemo, useState } from 'react';
import qrcode from 'qrcode-generator';
import { useAuth } from '../../auth/AuthContext.jsx';
import { crApi } from '../../api/cr.js';
import { useAdminQuery, useFlash } from '../../admin/hooks.js';
import { formatDateTime, formatDateTimeNoYear } from '../../admin/format.js';
import { PageHeader, ConfirmDialog, FormModal, SuccessFlash } from '../../components/admin/controls.jsx';
import { Button } from '../../components/ui/Button.jsx';
import { Select } from '../../components/ui/Select.jsx';
import { Modal } from '../../components/ui/Modal.jsx';
import { Badge } from '../../components/ui/Badge.jsx';
import { Alert } from '../../components/ui/Alert.jsx';
import { Spinner } from '../../components/ui/Spinner.jsx';
import { NoSection } from '../../cr/NoSection.jsx';
import { IconQr, IconCopy, IconCheckCircle, IconInfo } from '../../components/icons.jsx';

/**
 * CR attendance — the session CODE and signed QR payload are generated by
 * the backend and returned EXACTLY ONCE at creation. They are displayed in
 * the moment and never persisted to storage. Students mark attendance with
 * the code (or QR) while the 10-minute window is open.
 */

function SessionStatus({ session }) {
  const expired = session.status === 'open' && Date.now() >= new Date(session.expiresAt).getTime();
  if (session.status === 'cancelled') return <Badge variant="neutral">Cancelled</Badge>;
  if (expired) return <Badge variant="warning">Expired</Badge>;
  return <Badge variant="success">Active</Badge>;
}

/** The one-time result: big code + QR (rendered client-side, stays on-device). */
function SessionCodeModal({ open, onClose, result }) {
  const [copied, setCopied] = useState(false);
  const code = result?.code ?? '';
  const qr = result?.qr ?? '';
  const expires = result?.session?.expiresAt;

  let qrSvg = null;
  if (qr) {
    try {
      const gen = qrcode(0, 'M');
      gen.addData(qr);
      gen.make();
      qrSvg = gen.createSvgTag({ cellSize: 4, margin: 1, scalable: true });
    } catch { qrSvg = null; } // QR render failure must never break the code view
  }

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* clipboard unavailable — no-op */ }
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Attendance session started"
      className="max-w-md"
      footer={
        <>
          <Button variant="secondary" onClick={copy} icon={IconCopy}>{copied ? 'Copied!' : 'Copy code'}</Button>
          <Button onClick={onClose}>Done</Button>
        </>
      }
    >
      <div className="space-y-4">
        <Alert variant="info">
          Show this to your class now. The code is shown <span className="font-semibold">only this once</span> and the session expires in 10 minutes.
        </Alert>
        <div className="flex flex-col items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50/80 p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Attendance code</p>
          <p className="select-all font-mono text-3xl font-bold tracking-[0.3em] text-slate-900" aria-label={`Attendance code ${code}`}>{code}</p>
          {qrSvg && (
            <div
              className="rounded-lg bg-white p-2 shadow-soft [&_svg]:size-44"
              role="img"
              aria-label="QR code for students to scan"
              // qrcode-generator builds the SVG locally from the signed token — no network, no third party
              dangerouslySetInnerHTML={{ __html: qrSvg }}
            />
          )}
        </div>
        {expires && (
          <p className="text-center text-xs text-slate-500">Expires {formatDateTimeNoYear(expires)} PKT</p>
        )}
      </div>
    </Modal>
  );
}

function RecordsModal({ open, onClose, session }) {
  const [items, setItems] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!open || !session?._id) return undefined;
    let cancelled = false;
    setItems(null);
    setError(null);
    crApi.attendance.records(session._id, { limit: 200 })
      .then((res) => { if (!cancelled) setItems(res?.data ?? []); })
      .catch((err) => { if (!cancelled) setError(err); });
    return () => { cancelled = true; };
  }, [open, session]);

  return (
    <Modal open={open} onClose={onClose} title={`Present students — ${session?.subject?.name ?? ''}`} className="max-w-md">
      {error ? (
        <Alert variant="danger">{error.message}</Alert>
      ) : items === null ? (
        <div className="grid place-items-center py-8" role="status" aria-label="Loading attendance records"><Spinner className="size-6 text-primary-500" /></div>
      ) : items.length === 0 ? (
        <p className="rounded-xl bg-slate-50 px-4 py-6 text-center text-sm text-slate-500">No attendance recorded yet.</p>
      ) : (
        <ul className="divide-y divide-slate-100">
          {items.map((r) => (
            <li key={r._id} className="flex items-center justify-between gap-3 py-2.5">
              <div className="min-w-0">
                <p className="truncate text-sm font-medium text-slate-800">{r.student?.name ?? '—'}</p>
                <p className="text-xs text-slate-500">{r.student?.rollNo} · via {r.method}</p>
              </div>
              <IconCheckCircle className="size-4 shrink-0 text-emerald-500" />
            </li>
          ))}
        </ul>
      )}
    </Modal>
  );
}

export default function AttendancePage() {
  const { user } = useAuth();
  const section = user?.section;

  const [starting, setStarting] = useState(false); // "Start session" form modal
  const [codeResult, setCodeResult] = useState(null); // one-time code/QR result — shown AFTER the form closes
  const [cancelTarget, setCancelTarget] = useState(null);
  const [cancelBusy, setCancelBusy] = useState(false);
  const [cancelError, setCancelError] = useState(null);
  const [recordsFor, setRecordsFor] = useState(null);
  const [flash, showFlash] = useFlash();

  const { items: subjects } = useAdminQuery(() => crApi.subjects.list({ status: 'active', limit: 100 }), []);
  const { items, pagination, loading, error, reload } = useAdminQuery(
    () => crApi.attendance.listSessions({ limit: 20 }), []
  );

  const activeSubjects = useMemo(() => subjects.filter((s) => s.status === 'active'), [subjects]);

  if (!section) return <NoSection />;

  const createSession = async ({ subject }) => {
    const res = await crApi.attendance.createSession({ subject });
    reload();
    // FormModal closes the form right after this resolves; the code modal then mounts.
    setCodeResult(res?.data);
  };

  const confirmCancel = async () => {
    setCancelBusy(true);
    setCancelError(null);
    try {
      await crApi.attendance.cancelSession(cancelTarget._id);
      setCancelTarget(null);
      reload();
      showFlash('Session cancelled.');
    } catch (err) {
      setCancelError(err);
    } finally {
      setCancelBusy(false);
    }
  };

  const openSessions = items.filter((s) => s.status === 'open' && Date.now() < new Date(s.expiresAt).getTime());

  return (
    <div className="mx-auto max-w-4xl space-y-6">
      <PageHeader title="Attendance" description="Live attendance sessions with secure one-time codes.">
        <Button icon={IconQr} onClick={() => setStarting(true)} disabled={activeSubjects.length === 0}>Start session</Button>
      </PageHeader>

      <SuccessFlash message={flash} />

      {activeSubjects.length === 0 && (
        <Alert variant="info">You need at least one active subject before starting an attendance session.</Alert>
      )}

      {error ? (
        <div className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-soft">
          <p className="text-sm font-medium text-red-600">{error.message}</p>
          <div className="mt-3"><Button variant="secondary" size="sm" onClick={reload}>Try again</Button></div>
        </div>
      ) : loading ? (
        <div className="space-y-3">
          {Array.from({ length: 3 }).map((_, i) => <div key={i} className="h-24 skeleton-shimmer rounded-2xl" />)}
        </div>
      ) : items.length === 0 ? (
        <div className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-soft">
          <div className="flex flex-col items-center py-10 text-center">
            <IconQr className="size-10 text-slate-300" />
            <h3 className="mt-3 text-sm font-semibold text-slate-700">No attendance sessions yet.</h3>
            <p className="mt-1 max-w-sm text-sm text-slate-500">Start a session during class — students mark themselves present with a secure code that expires in 10 minutes.</p>
            {activeSubjects.length > 0 && (
              <div className="mt-5"><Button icon={IconQr} onClick={() => setStarting(true)}>Start session</Button></div>
            )}
          </div>
        </div>
      ) : (
        <ul className="space-y-3">
          {items.map((s) => {
            const isActive = s.status === 'open' && Date.now() < new Date(s.expiresAt).getTime();
            return (
              <li key={s._id} className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-soft">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="min-w-0">
                    <div className="flex flex-wrap items-center gap-2">
                      <p className="font-semibold text-slate-900">{s.subject?.name ?? '—'}</p>
                      <SessionStatus session={s} />
                    </div>
                    <p className="mt-1 text-sm text-slate-500">
                      {s.subject?.code} · opened {formatDateTime(s.opensAt)} PKT
                    </p>
                    <p className="text-xs text-slate-400">expires {formatDateTime(s.expiresAt)} PKT</p>
                  </div>
                  <div className="flex shrink-0 items-center gap-3">
                    <div className="text-right">
                      <p className="text-xl font-semibold text-slate-900">{s.attendanceCount ?? 0}</p>
                      <p className="text-xs text-slate-400">present</p>
                    </div>
                    <div className="flex flex-col gap-1">
                      <Button variant="secondary" size="sm" onClick={() => setRecordsFor(s)}>View</Button>
                      {isActive && (
                        <Button variant="ghost" size="sm" className="text-red-600 hover:bg-red-50" onClick={() => { setCancelTarget(s); setCancelError(null); }}>Cancel</Button>
                      )}
                    </div>
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      )}

      {pagination && pagination.totalPages > 1 && (
        <p className="text-sm text-slate-500">Showing the {items.length} most recent sessions.</p>
      )}

      <div className="flex items-start gap-3 rounded-xl border border-slate-100 bg-white/70 p-4 text-sm text-slate-500">
        <IconInfo className="mt-0.5 size-4 shrink-0 text-slate-400" />
        <p>
          Sessions last <span className="font-medium text-slate-600">10 minutes</span> from creation.
          The code is generated by the server, shown once, and never stored on this device.
          {openSessions.length > 0 && <span className="text-emerald-600 font-medium"> {openSessions.length} session{openSessions.length === 1 ? '' : 's'} currently active.</span>}
        </p>
      </div>

      <StartSessionForm
        open={starting}
        onClose={() => setStarting(false)}
        subjects={activeSubjects}
        submit={createSession}
      />

      {codeResult && (
        <SessionCodeModal open onClose={() => setCodeResult(null)} result={codeResult} />
      )}

      <RecordsModal open={Boolean(recordsFor)} onClose={() => setRecordsFor(null)} session={recordsFor} />

      <ConfirmDialog
        open={Boolean(cancelTarget)}
        onClose={() => setCancelTarget(null)}
        title="Cancel attendance session?"
        body={<p><span className="font-medium">{cancelTarget?.subject?.name}</span> will be cancelled immediately. Students already marked present keep their attendance.</p>}
        confirmLabel="Cancel session"
        onConfirm={confirmCancel}
        busy={cancelBusy}
        error={cancelError}
        danger
      />
    </div>
  );
}

function StartSessionForm({ open, onClose, subjects, submit }) {
  const [subject, setSubject] = useState('');
  const [errors, setErrors] = useState({});

  const onSubmit = async () => {
    const next = {};
    if (!subject) next.subject = 'Select a subject.';
    setErrors(next);
    if (Object.keys(next).length) throw new Error('Please fix the highlighted fields.');
    await submit({ subject });
  };

  return (
    <FormModal open={open} onClose={onClose} title="Start attendance session" submitLabel="Start session" onSubmit={onSubmit}>
      {(fieldErrors) => (
        <>
          <Alert variant="info">A one-time code and QR will be generated for a 10-minute window.</Alert>
          <Select label="Subject" required id="att-subject" value={subject} onChange={(e) => setSubject(e.target.value)} error={errors.subject ?? fieldErrors?.subject ?? null}>
            <option value="">Select subject…</option>
            {subjects.map((s) => <option key={s._id} value={s._id}>{s.code} — {s.name}</option>)}
          </Select>
        </>
      )}
    </FormModal>
  );
}
